# Generated by Django 4.2.1 on 2023-05-22 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField()),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.emotion')),
            ],
        ),
    ]
